# Generated by Django 3.2.1 on 2021-05-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OMApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryteam',
            name='Next_Activate_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Estimated_Delivery_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Placed_Time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='Order_Number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMApp.orderdetails'),
        ),
    ]
