# Generated by Django 3.2.1 on 2021-05-16 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMApp', '0002_auto_20210516_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryteam',
            name='Next_Activate_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 0, 24, 22, 507587)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Estimated_Delivery_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 0, 24, 22, 508584)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Placed_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 17, 0, 24, 22, 508584)),
        ),
    ]
