# Generated by Django 3.2.1 on 2021-05-22 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMApp', '0003_auto_20210517_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryteam',
            name='Next_Activate_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 19, 4, 45, 443929)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Estimated_Delivery_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 19, 4, 45, 444926)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Placed_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 19, 4, 45, 444926)),
        ),
    ]
