# Generated by Django 3.2.1 on 2021-05-22 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OMApp', '0004_auto_20210522_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryteam',
            name='Next_Activate_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 23, 1, 46, 761876)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Estimated_Delivery_Time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 22, 23, 1, 46, 762874)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='Placed_Time',
            field=models.DateTimeField(default='2021-05-22 23:01'),
        ),
    ]
